-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 21:45:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectgym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectgym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectgym` DEFAULT CHARACTER SET utf8 ;
USE `projectgym` ;

-- -----------------------------------------------------
-- Table `projectgym`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`usuario_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`usuario_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificacion` INT UNSIGNED NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_usuario_contacto_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_contacto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projectgym`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`usuario_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`usuario_estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estatura` DOUBLE NOT NULL,
  `peso` DOUBLE NOT NULL,
  `fecha` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_usuario_estado_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_estado_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projectgym`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `departamento_id`),
  INDEX `fk_municipio_departamento1_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_municipio_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `projectgym`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`barrio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `municipio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `municipio_id`),
  INDEX `fk_barrio_municipio1_idx` (`municipio_id` ASC),
  CONSTRAINT `fk_barrio_municipio1`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `projectgym`.`municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`sede` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `barrio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `barrio_id`),
  INDEX `fk_sede_barrio1_idx` (`barrio_id` ASC),
  CONSTRAINT `fk_sede_barrio1`
    FOREIGN KEY (`barrio_id`)
    REFERENCES `projectgym`.`barrio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`tipo_recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`tipo_recurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`recurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `tipo_recurso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_recurso_id`),
  INDEX `fk_recurso_tipo_recurso1_idx` (`tipo_recurso_id` ASC),
  CONSTRAINT `fk_recurso_tipo_recurso1`
    FOREIGN KEY (`tipo_recurso_id`)
    REFERENCES `projectgym`.`tipo_recurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`ejercicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` DATETIME NOT NULL,
  `hora_fin` DATETIME NOT NULL,
  `recurso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `recurso_id`),
  INDEX `fk_ejercicio_recurso1_idx` (`recurso_id` ASC),
  CONSTRAINT `fk_ejercicio_recurso1`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `projectgym`.`recurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`usuario_ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`usuario_ejercicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `ejercicio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `ejercicio_id`),
  INDEX `fk_usuario_ejercicio_ejercicio1_idx` (`ejercicio_id` ASC),
  CONSTRAINT `fk_usuario_ejercicio_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projectgym`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ejercicio_ejercicio1`
    FOREIGN KEY (`ejercicio_id`)
    REFERENCES `projectgym`.`ejercicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`suscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `activo` TINYINT NULL DEFAULT 1,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_suscripcion_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_suscripcion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projectgym`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectgym`.`recurso_sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectgym`.`recurso_sede` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recurso_id` INT NOT NULL,
  `sede_id` INT NOT NULL,
  PRIMARY KEY (`id`, `recurso_id`, `sede_id`),
  INDEX `fk_recurso_has_sede_sede1_idx` (`sede_id` ASC),
  INDEX `fk_recurso_has_sede_recurso1_idx` (`recurso_id` ASC),
  CONSTRAINT `fk_recurso_has_sede_recurso1`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `projectgym`.`recurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recurso_has_sede_sede1`
    FOREIGN KEY (`sede_id`)
    REFERENCES `projectgym`.`sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
